# Generated by Django 4.0.4 on 2022-05-24 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('uname', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Patel Javal Kalpeshbhai', max_length=100)),
                ('upi_id', models.CharField(default='6351489115@paytm', max_length=25)),
                ('uname', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='login1.user')),
            ],
        ),
    ]
